import test from 'node:test';import assert from 'node:assert/strict';import {initialState,transition,ACTIONS} from '../skills/woia-compliance/scripts/provider.mjs';import {digest} from '../skills/woia-compliance/scripts/guard.mjs';
const payload={evidence_refs:['synthetic-evidence'],facts:{synthetic:'yes'},record_id:'record',reason:'accepted-policy',outcome:'accepted',rule_id:'synthetic',hold_scope:'doc'};
function pair(action,p=payload,id='op'){const c={action,payload:p,operation_id:id,organization:'org',resource:'doc',purpose:'review'};const x={authenticated:true,actor:'agent',organization:'org',department:'legal-compliance',now:100,policy_version:'p1',source_current:true,accepted_policy:{accepted:true,version:'p1',organization:'org',resource:'doc',purposes:['review'],criteria:[{id:'synthetic',allowed_values:['yes']}],exception_rules:['synthetic'],allowed_decisions:['accepted'],retention:{retain_until:50,disposal_permitted:true}},competent_decision:{accepted:true,actor:'competent-human',evidence_ref:'decision',command_digest:digest(c),policy_version:'p1'}};x.grant={action,command_digest:digest(c),actor:'agent',organization:'org',resource:'doc',purpose:'review',expires_at:200,policy_version:'p1'};return [c,x];}
const run=(s,a,p,id)=>transition(s,...pair(a,p,id));
test('review evaluates accepted criteria not legal opinion',()=>{const out=run(initialState(),ACTIONS[0]);assert.equal(out.result.status,'POLICY_MATCH');assert.equal(out.result.legal_opinion,false);assert.equal(out.state.records.length,1);});
test('missing fact stays insufficient evidence and contradictory fact mismatches policy',()=>{assert.equal(run(initialState(),ACTIONS[0],{...payload,facts:{}}).result.status,'INSUFFICIENT_EVIDENCE');assert.equal(run(initialState(),ACTIONS[0],{...payload,facts:{synthetic:'no'}}).result.status,'POLICY_MISMATCH');});
test('missing or unaccepted applicability blocks instead of inventing law',()=>{const [c,x]=pair(ACTIONS[0]);x.accepted_policy.accepted=false;assert.throws(()=>transition(initialState(),c,x),/APPLICABLE_POLICY/);});
test('decision records exact competent evidence with immutable unique ID',()=>{const s=run(initialState(),ACTIONS[1]).state;assert.equal(s.records[0].decision.actor,'competent-human');assert.throws(()=>run(s,ACTIONS[1],payload,'new-operation'),/IMMUTABLE/);assert.equal(run(s,ACTIONS[1]).state.records.length,1);});
test('decision requires named accepted exact competent authorization',()=>{for(const edit of [x=>x.competent_decision.accepted=false,x=>x.competent_decision.actor=null,x=>x.competent_decision.command_digest='bad']){const [c,x]=pair(ACTIONS[1]);edit(x);assert.throws(()=>transition(initialState(),c,x),/COMPETENT/);}});
test('unknown decision outcome is not granted by technical access',()=>{assert.throws(()=>run(initialState(),ACTIONS[1],{...payload,outcome:'invented'}),/OUTCOME/);});
test('exception requires accepted policy-specific exception rule',()=>{assert.equal(run(initialState(),ACTIONS[2]).result.status,'RECORDED');assert.throws(()=>run(initialState(),ACTIONS[2],{...payload,rule_id:'invented'}),/EXCEPTION/);});
test('hold record prevents retention disposal and never disappears on elapsed time',()=>{const s=run(initialState(),ACTIONS[3]).state;assert.equal(run(s,ACTIONS[4],{evidence_refs:['e']},'resolve').result.disposal,'BLOCKED_HOLD');});
test('hold requires exact resource scope',()=>{assert.throws(()=>run(initialState(),ACTIONS[3],{...payload,hold_scope:'other'}),/SCOPE/);});
test('retention resolution is eligibility only not disposal authority',()=>{assert.equal(run(initialState(),ACTIONS[4],{evidence_refs:['e']}).result.disposal,'ELIGIBLE_REQUIRES_DOCUMENT_DISPOSAL_AUTHORITY');const [c,x]=pair(ACTIONS[4],{evidence_refs:['e']});x.accepted_policy.retention.retain_until=150;assert.equal(transition(initialState(),c,x).result.disposal,'RETAIN');});
test('non Legal actor stale policy missing evidence revoked grant all fail closed',()=>{for(const edit of [x=>x.department='finance',x=>x.accepted_policy.version='old',x=>x.grant.revoked=true]){const [c,x]=pair(ACTIONS[0]);edit(x);assert.throws(()=>transition(initialState(),c,x));}assert.throws(()=>run(initialState(),ACTIONS[0],{evidence_refs:[]}),/EVIDENCE/);});
test('idempotency conflict preserves prior decision without rewriting original record',()=>{const s=run(initialState(),ACTIONS[1]).state;assert.throws(()=>run(s,ACTIONS[1],{...payload,reason:'changed'}),/IDEMPOTENCY/);assert.equal(s.records[0].reason,'accepted-policy');});
